# Generated by Django 3.1.12 on 2024-11-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email_id',
            new_name='email',
        ),
        
        migrations.RenameField(
            model_name='employee',
            old_name='mobile_no',
            new_name='mobile_number',
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
